# Generated by Django 4.2 on 2023-05-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='templates.member')),
            ],
        ),
        migrations.CreateModel(
            name='Template_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('size', models.IntegerField()),
                ('pont', models.CharField(max_length=50)),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('angle', models.FloatField()),
                ('text_color', models.CharField(max_length=50)),
                ('background_color', models.CharField(max_length=50)),
                ('transparency', models.FloatField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.ForeignKey(db_column='template_type_id', on_delete=django.db.models.deletion.CASCADE, to='templates.template_type'),
        ),
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('src_type', models.CharField(max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('curvature', models.FloatField()),
                ('transparency', models.FloatField()),
                ('angle', models.FloatField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
            ],
        ),
    ]
