# Generated by Django 4.2.1 on 2023-05-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Introduce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_image_src", models.CharField(default="", max_length=255)),
                ("full_image_src", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("nick_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "introduce",
                    models.ForeignKey(
                        db_column="introduce_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.introduce",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("size", models.IntegerField()),
                ("pont", models.CharField(max_length=50)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("angle", models.FloatField()),
                ("text_color", models.CharField(max_length=50)),
                ("back_color", models.CharField(max_length=50)),
                ("cursive", models.FloatField()),
                ("align", models.BooleanField(default=False)),
                ("line", models.CharField(max_length=50)),
                ("textopa", models.FloatField()),
                ("backopa", models.FloatField()),
                ("zindex", models.IntegerField()),
                (
                    "template",
                    models.ForeignKey(
                        db_column="template_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100)),
                (
                    "introduce",
                    models.ForeignKey(
                        db_column="introduce_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.introduce",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="template_category",
            field=models.ForeignKey(
                db_column="category_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="templates.templatecategory",
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("height", models.FloatField()),
                ("width", models.FloatField()),
                ("cursive", models.FloatField()),
                ("transparency", models.FloatField()),
                ("angle", models.FloatField()),
                (
                    "template",
                    models.ForeignKey(
                        db_column="template_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.template",
                    ),
                ),
            ],
        ),
    ]
