# Generated by Django 4.2.1 on 2023-05-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template", old_name="template_category", new_name="category",
        ),
        migrations.RenameField(
            model_name="templatetag", old_name="tag_name", new_name="name",
        ),
    ]
