# Generated by Django 4.2.1 on 2023-05-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_remove_templatetag_introduce_templatetag_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="templatetag", old_name="name", new_name="tag_name",
        ),
    ]
