# Generated by Django 4.2.1 on 2023-05-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0004_rename_name_templatetag_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetag",
            name="Template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="templates.template"
            ),
        ),
    ]
