# Generated by Django 4.2.1 on 2023-05-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0006_alter_templatetag_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template", old_name="category", new_name="template_category",
        ),
    ]
