# Generated by Django 4.2.1 on 2023-05-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0007_rename_category_template_template_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="templatetag", old_name="Template", new_name="template",
        ),
    ]
