# Generated by Django 4.2.1 on 2023-05-25 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0008_rename_template_templatetag_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image", old_name="cursive", new_name="blur",
        ),
        migrations.RenameField(
            model_name="image", old_name="angle", new_name="border_size",
        ),
        migrations.RenameField(
            model_name="image", old_name="transparency", new_name="brightness",
        ),
        migrations.RemoveField(model_name="text", name="angle",),
        migrations.RemoveField(model_name="text", name="line",),
        migrations.AddField(
            model_name="image",
            name="border_color",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="border_style",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="contrast",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="gray_scale",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="hue",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="invert",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="opacity",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="radis",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="saturate",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="sepia",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="src",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="zindex",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="text", name="bold", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="text", name="italic", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="text",
            name="underline",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="templatetag",
            name="template",
            field=models.ForeignKey(
                db_column="template_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="templates.template",
            ),
        ),
    ]
