# Generated by Django 4.2.1 on 2023-05-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0009_rename_cursive_image_blur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="height",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="template",
            name="width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
