# Generated by Django 4.2.1 on 2023-05-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0010_template_height_template_width"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image", old_name="border_color", new_name="bordercolor",
        ),
        migrations.RenameField(
            model_name="image", old_name="border_size", new_name="bordersize",
        ),
        migrations.RenameField(
            model_name="image", old_name="invert", new_name="radius",
        ),
        migrations.RemoveField(model_name="image", name="radis",),
        migrations.AlterField(
            model_name="template",
            name="introduce",
            field=models.ForeignKey(
                db_column="introduce_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="templates.introduce",
            ),
        ),
    ]
