# Generated by Django 4.2.1 on 2023-05-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0011_rename_border_color_image_bordercolor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image", old_name="bordercolor", new_name="border_color",
        ),
        migrations.RenameField(
            model_name="image", old_name="bordersize", new_name="border_size",
        ),
    ]
