# Generated by Django 4.2.1 on 2023-05-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0012_rename_bordercolor_image_border_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image", old_name="radius", new_name="invert",
        ),
        migrations.RenameField(model_name="text", old_name="pont", new_name="font",),
        migrations.RenameField(
            model_name="text", old_name="underline", new_name="underlined",
        ),
        migrations.AddField(
            model_name="image",
            name="radis",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="template",
            name="introduce",
            field=models.ForeignKey(
                db_column="introduce_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="templates.introduce",
            ),
            preserve_default=False,
        ),
    ]
