# Generated by Django 4.2.1 on 2023-05-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0014_rename_border_color_image_boardstyle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="text", old_name="back_color", new_name="backcolor",
        ),
        migrations.RenameField(
            model_name="text", old_name="text_color", new_name="textcolor",
        ),
    ]
